# Generated by Django 2.2.3 on 2019-09-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('caddr', models.CharField(blank=True, max_length=100)),
                ('cphone', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
