# Generated by Django 2.2.3 on 2019-09-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
