# Generated by Django 2.2.3 on 2019-10-16 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191016_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tprofile',
            old_name='tname',
            new_name='user',
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acontent', models.CharField(max_length=100)),
                ('aclass', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tprofile')),
            ],
        ),
    ]
